"""Orvix shared wire protocol models."""

from orvix_protocol.protocol import (
    AnyMessage,
    BaseMessage,
    EmbeddingJobDispatchMessage,
    GPUMetrics,
    GPUInfo,
    HeartbeatMessage,
    ImageJobCompleteMessage,
    ImageJobDispatchMessage,
    ImageJobFailedMessage,
    JobChunkMessage,
    JobMessage,
    JobResultMessage,
    PingMessage,
    RegisterAckMessage,
    RegisterMessage,
    ShutdownMessage,
    VideoJobCompleteMessage,
    VideoJobDispatchMessage,
    VideoJobFailedMessage,
    parse_message,
    serialize,
)

__all__ = [
    "AnyMessage",
    "BaseMessage",
    "EmbeddingJobDispatchMessage",
    "GPUMetrics",
    "GPUInfo",
    "HeartbeatMessage",
    "ImageJobCompleteMessage",
    "ImageJobDispatchMessage",
    "ImageJobFailedMessage",
    "JobChunkMessage",
    "JobMessage",
    "JobResultMessage",
    "PingMessage",
    "RegisterAckMessage",
    "RegisterMessage",
    "ShutdownMessage",
    "VideoJobCompleteMessage",
    "VideoJobDispatchMessage",
    "VideoJobFailedMessage",
    "parse_message",
    "serialize",
]
