"""Token intelligence endpoints: token/CA scans + accumulation.

Authenticated with EITHER a wallet JWT or an `orvx_sk_` API key (scans spend
Solana RPC + Jupiter calls, so they are not public). Degrade gracefully: fields
the data sources cannot answer come back null/[].
"""

from fastapi import APIRouter, Depends
from solders.pubkey import Pubkey
from supabase import Client

from app.config import settings
from app.database import get_supabase
from app.dependencies import get_current_user_flexible
from app.exceptions import OrvixException, ValidationError
from app.models.intel import (
    AccumulationResponse,
    EarlyBuyerEntry,
    SocialAnalysisResponse,
    TokenHolderSnapshot,
    TokenIntelligenceResponse,
    TokenScanResponse,
    WalletClusterResponse,
)
from app.services import holder_intel, intel_ai, rate_limit_service, social_intel, tier_service, token_intel

router = APIRouter(prefix="/v1/tokens", tags=["tokens"])


def _validate_address(address: str, label: str) -> None:
    try:
        Pubkey.from_string(address)
    except Exception as exc:  # noqa: BLE001 — solders raises ValueError
        raise ValidationError(f"Invalid Solana address for {label}") from exc


def _rate_limit(current_user: dict) -> None:
    """Throttle scan endpoints: they spend external RPC/Jupiter budget."""
    tier = tier_service.tier_for_stake(current_user.get("staked_orvx"))
    rate_limit_service.check_user(current_user["id"], tier, bucket="intel")


@router.get("/{ca}", response_model=TokenScanResponse)
async def get_token_scan(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """Full profile for a token mint: metadata, supply, price, liquidity, risk."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await token_intel.scan_token(db, ca)


@router.get("/{ca}/accumulation", response_model=AccumulationResponse)
async def get_accumulation(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """Accumulation score (0-100) + metrics for a token mint."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await token_intel.compute_accumulation(db, ca)


@router.get("/{ca}/intelligence", response_model=TokenIntelligenceResponse)
async def get_token_intelligence(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """AI-written analysis of a token, generated by an ORVX GPU node.

    The scan + accumulation results are handed to a chat model running on the
    compute network; the response is its narrative/risk summary. When no node
    serves the analysis model the endpoint returns 503 (no_chat_provider) —
    the intelligence layer is exactly where the network should be reachable.
    """
    _validate_address(ca, "token")
    _rate_limit(current_user)
    result = await intel_ai.generate_token_intelligence(db, ca)
    if result is None:
        reason = _node_reason()
        if reason == "at_capacity":
            raise OrvixException(
                "All compute providers serving this model are busy. Retry shortly.",
                error_code="capacity_exhausted",
                status_code=503,
            )
        raise OrvixException(
            "No compute providers are currently available",
            error_code="no_chat_provider",
            status_code=503,
        )
    return result


@router.get("/{ca}/holders", response_model=TokenHolderSnapshot)
async def get_token_holders(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """Real top-holder distribution for a mint, resolved to owner wallets."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await holder_intel.top_holders(db, ca)


@router.get("/{ca}/early-buyers", response_model=list[EarlyBuyerEntry])
async def get_early_buyers(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """First-buy evidence for the current top holders, oldest buy first."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await holder_intel.early_buyers(db, ca)


@router.get("/{ca}/social", response_model=SocialAnalysisResponse)
async def get_social_analysis(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """Social media analysis for a token: DexScreener data, Twitter metrics, sentiment."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await social_intel.analyze_social(db, ca)


@router.get("/{ca}/clusters", response_model=WalletClusterResponse)
async def get_wallet_clusters(
    ca: str,
    current_user: dict = Depends(get_current_user_flexible),
    db: Client = Depends(get_supabase),
):
    """Detect coordinated wallet clusters among top holders."""
    _validate_address(ca, "token")
    _rate_limit(current_user)
    return await holder_intel.detect_clusters(db, ca)


def _node_reason() -> str:
    from app.services.node_manager import node_manager

    return node_manager.unavailable_reason(settings.INTEL_AI_MODEL)
